// ===== Mock Data for Duolingo Creator Studio =====

const MOCK_MY_VIDEOS = [
  {
    id: 1,
    title: "Ordering Tacos in Mexico City",
    language: "Spanish",
    level: "A2",
    category: "conversation",
    score: 94,
    views: 48200,
    studyActions: 7100,
    status: "published",
    date: "2026-03-10",
    tags: ["food", "travel"],
  },
  {
    id: 2,
    title: "10 Phrases You Hear at the Market",
    language: "Spanish",
    level: "A1",
    category: "vocab",
    score: 91,
    views: 35800,
    studyActions: 5400,
    status: "published",
    date: "2026-03-07",
    tags: ["shopping", "daily"],
  },
  {
    id: 3,
    title: "How to Complain Politely in Spanish",
    language: "Spanish",
    level: "B1",
    category: "conversation",
    score: 87,
    views: 29100,
    studyActions: 4200,
    status: "published",
    date: "2026-03-03",
    tags: ["daily", "work"],
  },
  {
    id: 4,
    title: "Slang Your Textbook Won't Teach You",
    language: "Spanish",
    level: "B2",
    category: "slang",
    score: 72,
    views: 61400,
    studyActions: 3800,
    status: "published",
    date: "2026-02-28",
    tags: ["music"],
  },
  {
    id: 5,
    title: "Ask for Directions Like a Local",
    language: "Spanish",
    level: "A2",
    category: "travel",
    score: 88,
    views: 22300,
    studyActions: 3100,
    status: "published",
    date: "2026-02-22",
    tags: ["travel"],
  },
  {
    id: 6,
    title: "Subjunctive in 45 Seconds",
    language: "Spanish",
    level: "B2",
    category: "grammar",
    score: null,
    views: 0,
    studyActions: 0,
    status: "draft",
    date: "2026-03-12",
    tags: [],
  },
];

const MOCK_TOP_VIDEOS = [
  { title: "Ordering Tacos in Mexico City", views: 48200, studyActions: 7100, score: 94, retention: "82%" },
  { title: "10 Phrases You Hear at the Market", views: 35800, studyActions: 5400, score: 91, retention: "79%" },
  { title: "Slang Your Textbook Won't Teach You", views: 61400, studyActions: 3800, score: 72, retention: "64%" },
  { title: "How to Complain Politely", views: 29100, studyActions: 4200, score: 87, retention: "76%" },
  { title: "Ask for Directions Like a Local", views: 22300, studyActions: 3100, score: 88, retention: "74%" },
];

const MOCK_CHART_DATA = [
  { day: "Feb 12", views: 4200, actions: 620 },
  { day: "Feb 15", views: 5100, actions: 780 },
  { day: "Feb 18", views: 4800, actions: 710 },
  { day: "Feb 21", views: 6200, actions: 920 },
  { day: "Feb 24", views: 7800, actions: 1150 },
  { day: "Feb 27", views: 8400, actions: 1240 },
  { day: "Mar 02", views: 9100, actions: 1380 },
  { day: "Mar 05", views: 11200, actions: 1650 },
  { day: "Mar 08", views: 12800, actions: 1890 },
  { day: "Mar 11", views: 14100, actions: 2100 },
];

const STRENGTH_POOL = [
  "Clear, well-paced speech throughout",
  "Accurate hardcoded subtitles detected",
  "Vocabulary matches the tagged learner level",
  "Real-world scenario adds practical context",
  "Good repetition of key phrases",
  "Visual context supports comprehension",
  "Natural conversation flow",
  "Engaging hook in the first 3 seconds",
  "Appropriate video length for the content",
];

const SUGGESTION_POOL = [
  "Consider adding a slow-speech replay at the end",
  "A quick on-screen vocab summary would boost retention",
  "Background music is slightly loud — lower it 2-3 dB",
  "Adding a 'repeat after me' pause would increase study actions",
  "Try showing the phrase written on screen while speaking",
  "Consider a brief English translation for A1 learners",
  "Ending with a question prompt would drive more comments",
  "Trim the first 2 seconds — get to the content faster",
];
